[tool.poetry]
name = "shopsdk"
version = "0.1.0"
description = ""
authors = ["6100m <gloom@wiilink24.com>"]

[tool.poetry.dependencies]
python = "^3.8"
sendgrid = "^6.4.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
