"""Add logs table

Revision ID: 01cda65b0957
Revises: af7d7a8e8309
Create Date: 2025-02-03 15:47:47.893623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01cda65b0957'
down_revision = 'af7d7a8e8309'
branch_labels = None
depends_on = None


def upgrade():
    op.execute(
        """
create table logs
(
    id     serial
        primary key,
    action varchar not null,
    "user" varchar not null
    timestamp timestamp not null
);
     """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
