"""Remove locale from movies

Revision ID: 03d6c029c301
Revises: 9a8595b5d3ac
Create Date: 2026-06-30 09:17:55.565084

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "03d6c029c301"
down_revision = "9a8595b5d3ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("movies", schema=None) as batch_op:
        batch_op.drop_column("locale")

    with op.batch_alter_table("pay_movies", schema=None) as batch_op:
        batch_op.drop_column("locale")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pay_movies", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "locale",
                postgresql.ENUM(
                    "jp",
                    "Ge",
                    "En",
                    "Fr",
                    "Sp",
                    "Du",
                    "It",
                    "ptbr",
                    "ru",
                    name="locale",
                ),
                autoincrement=False,
                nullable=False,
            )
        )

    with op.batch_alter_table("movies", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "locale",
                postgresql.ENUM(
                    "jp",
                    "Ge",
                    "En",
                    "Fr",
                    "Sp",
                    "Du",
                    "It",
                    "ptbr",
                    "ru",
                    name="locale",
                ),
                autoincrement=False,
                nullable=False,
            )
        )

    # ### end Alembic commands ###
