"""Add price code and reference id to PayMovies

Revision ID: 083122793626
Revises: 01a299e3292d
Create Date: 2022-11-03 09:55:59.743479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "083122793626"
down_revision = "01a299e3292d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pay_movies", sa.Column("reference_id", sa.String(length=32), nullable=False)
    )
    op.add_column(
        "pay_movies",
        sa.Column("price_code", sa.Integer(), autoincrement=True, nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pay_movies", "price_code")
    op.drop_column("pay_movies", "reference_id")
    # ### end Alembic commands ###
