"""Some pay poster stuff

Revision ID: 0ed7c094d1e4
Revises: 10a4bee2f951
Create Date: 2023-06-01 10:46:33.690363

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0ed7c094d1e4"
down_revision = "10a4bee2f951"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("giveaways", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.create_unique_constraint(None, "giveaways", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "giveaways", type_="unique")
    op.alter_column("giveaways", "email", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
