"""Add Giveaways table

Revision ID: 10a4bee2f951
Revises: 083122793626
Create Date: 2023-02-27 10:06:42.505002

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "10a4bee2f951"
down_revision = "083122793626"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "giveaways",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("giveaway_id", sa.Integer(), nullable=False),
        sa.Column("wii_id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("giveaways")
    # ### end Alembic commands ###
