"""Initial tracking

Revision ID: 370098b22554
Revises: 
Create Date: 2021-03-22 12:35:28.649670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "370098b22554"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "categories", ["category_id"])
    op.create_unique_constraint(None, "concierge_miis", ["mii_id"])
    op.drop_column("concierge_miis", "update_date")
    op.create_unique_constraint(None, "movies", ["movie_id"])
    op.create_unique_constraint(None, "new_movies", ["movie_id"])
    op.create_unique_constraint(None, "news", ["id"])
    op.add_column("pay_categories", sa.Column("genre_id", sa.Integer(), nullable=True))
    op.create_unique_constraint(None, "pay_categories", ["category_id"])
    op.create_unique_constraint(None, "pay_category_headers", ["title"])
    op.create_unique_constraint(None, "pay_movies", ["movie_id"])
    op.create_unique_constraint(None, "pay_posters", ["poster_id"])
    op.create_unique_constraint(None, "posters", ["poster_id"])
    op.create_unique_constraint(None, "room_menu", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "room_menu", type_="unique")
    op.drop_constraint(None, "posters", type_="unique")
    op.drop_constraint(None, "pay_posters", type_="unique")
    op.drop_constraint(None, "pay_movies", type_="unique")
    op.drop_constraint(None, "pay_category_headers", type_="unique")
    op.drop_constraint(None, "pay_categories", type_="unique")
    op.drop_column("pay_categories", "genre_id")
    op.drop_constraint(None, "news", type_="unique")
    op.drop_constraint(None, "new_movies", type_="unique")
    op.drop_constraint(None, "movies", type_="unique")
    op.add_column(
        "concierge_miis",
        sa.Column(
            "update_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "concierge_miis", type_="unique")
    op.drop_constraint(None, "categories", type_="unique")
    # ### end Alembic commands ###
