"""Add ConciergeMovies table

Revision ID: 42bc7a8c4eb9
Revises: 162fb1102c9b
Create Date: 2024-07-01 12:47:22.514079

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "42bc7a8c4eb9"
down_revision = "162fb1102c9b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("concierge_movies", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("concierge_movies", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
