"""Remove locale from movie credits and giveaways

Revision ID: 7e2d8bff82e0
Revises: c0db4fbbc1ed
Create Date: 2026-06-30 09:29:23.664240

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7e2d8bff82e0"
down_revision = "c0db4fbbc1ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("giveaways", schema=None) as batch_op:
        batch_op.drop_column("locale")

    with op.batch_alter_table("movie_credits", schema=None) as batch_op:
        batch_op.drop_column("locale")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("movie_credits", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "locale",
                postgresql.ENUM(
                    "jp",
                    "Ge",
                    "En",
                    "Fr",
                    "Sp",
                    "Du",
                    "It",
                    "ptbr",
                    "ru",
                    name="locale",
                ),
                autoincrement=False,
                nullable=False,
            )
        )

    with op.batch_alter_table("giveaways", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "locale",
                postgresql.ENUM(
                    "jp",
                    "Ge",
                    "En",
                    "Fr",
                    "Sp",
                    "Du",
                    "It",
                    "ptbr",
                    "ru",
                    name="locale",
                ),
                autoincrement=False,
                nullable=False,
            )
        )

    # ### end Alembic commands ###
