"""Refactor models

Revision ID: 9a3ca245cede
Revises: e4bbd06caf28
Create Date: 2026-06-14 20:53:18.972020

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9a3ca245cede"
down_revision = "e4bbd06caf28"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=False)

    with op.batch_alter_table("evaluate_data", schema=None) as batch_op:
        batch_op.alter_column("movie_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("gender", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("blood", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("age", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("vote", existing_type=sa.INTEGER(), nullable=False)

    with op.batch_alter_table("intro_info", schema=None) as batch_op:
        batch_op.alter_column(
            "cnt_type",
            existing_type=postgresql.ENUM("Video", "Image", name="contenttypes"),
            nullable=False,
        )
        batch_op.alter_column(
            "link_type",
            existing_type=postgresql.ENUM(
                "Regular",
                "TheatreMovie",
                "TheatreCategory",
                "Shop",
                "Room",
                "Category",
                name="linktypes",
            ),
            nullable=False,
        )

    with op.batch_alter_table("mii_data", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["mii_id"])

    with op.batch_alter_table("movie_credits", schema=None) as batch_op:
        batch_op.alter_column("movie_id", existing_type=sa.INTEGER(), nullable=False)

    with op.batch_alter_table("pay_categories", schema=None) as batch_op:
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=False)

    with op.batch_alter_table("poll_data", schema=None) as batch_op:
        batch_op.alter_column("poll_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("wii_num", existing_type=sa.BIGINT(), nullable=False)
        batch_op.alter_column("choice", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("age", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("gender", existing_type=sa.INTEGER(), nullable=False)

    with op.batch_alter_table("room_menu", schema=None) as batch_op:
        batch_op.alter_column("room_id", existing_type=sa.INTEGER(), nullable=False)

    with op.batch_alter_table("room_miis", schema=None) as batch_op:
        batch_op.alter_column("mii_msg", existing_type=sa.VARCHAR(), nullable=False)

    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.alter_column(
            "bgm",
            existing_type=postgresql.ENUM(
                "SOFT_GUITAR",
                "NORMAL",
                "FOLK",
                "JAZZY",
                "TRUMPET",
                "CHIMES",
                "WESTERN",
                "HARP",
                name="roombgmtypes",
            ),
            nullable=False,
        )
        batch_op.alter_column("parade_mii", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("mascot", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("intro_msg", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "contact_data", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column("news", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("level", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.alter_column("level", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("news", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("contact_data", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("intro_msg", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("mascot", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("parade_mii", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column(
            "bgm",
            existing_type=postgresql.ENUM(
                "SOFT_GUITAR",
                "NORMAL",
                "FOLK",
                "JAZZY",
                "TRUMPET",
                "CHIMES",
                "WESTERN",
                "HARP",
                name="roombgmtypes",
            ),
            nullable=True,
        )

    with op.batch_alter_table("room_miis", schema=None) as batch_op:
        batch_op.alter_column("mii_msg", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("room_menu", schema=None) as batch_op:
        batch_op.alter_column("room_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("poll_data", schema=None) as batch_op:
        batch_op.alter_column("gender", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("age", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("choice", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("wii_num", existing_type=sa.BIGINT(), nullable=True)
        batch_op.alter_column("poll_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("pay_categories", schema=None) as batch_op:
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("movie_credits", schema=None) as batch_op:
        batch_op.alter_column("movie_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("mii_data", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("intro_info", schema=None) as batch_op:
        batch_op.alter_column(
            "link_type",
            existing_type=postgresql.ENUM(
                "Regular",
                "TheatreMovie",
                "TheatreCategory",
                "Shop",
                "Room",
                "Category",
                name="linktypes",
            ),
            nullable=True,
        )
        batch_op.alter_column(
            "cnt_type",
            existing_type=postgresql.ENUM("Video", "Image", name="contenttypes"),
            nullable=True,
        )

    with op.batch_alter_table("evaluate_data", schema=None) as batch_op:
        batch_op.alter_column("vote", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("age", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("blood", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("gender", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("movie_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###
