"""Add locale to forgotten columns

Revision ID: 9a8595b5d3ac
Revises: cf6f2d53acba
Create Date: 2026-06-28 11:45:57.307766

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9a8595b5d3ac"
down_revision = "cf6f2d53acba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("news", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "locale",
                sa.Enum(
                    "jp",
                    "Ge",
                    "En",
                    "Fr",
                    "Sp",
                    "Du",
                    "It",
                    "ptbr",
                    "ru",
                    name="locale",
                ),
                nullable=True,
            )
        )

    op.execute("""UPDATE news SET locale='En'""")
    with op.batch_alter_table("news", schema=None) as batch_op:
        batch_op.alter_column("locale", nullable=False)

    with op.batch_alter_table("pay_posters", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "locale",
                sa.Enum(
                    "jp",
                    "Ge",
                    "En",
                    "Fr",
                    "Sp",
                    "Du",
                    "It",
                    "ptbr",
                    "ru",
                    name="locale",
                ),
                nullable=True,
            )
        )

    op.execute("""UPDATE pay_posters SET locale='En'""")
    with op.batch_alter_table("pay_posters", schema=None) as batch_op:
        batch_op.alter_column("locale", nullable=False)

    with op.batch_alter_table("posters", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "locale",
                sa.Enum(
                    "jp",
                    "Ge",
                    "En",
                    "Fr",
                    "Sp",
                    "Du",
                    "It",
                    "ptbr",
                    "ru",
                    name="locale",
                ),
                nullable=True,
            )
        )

    op.execute("""UPDATE posters SET locale='En'""")
    with op.batch_alter_table("posters", schema=None) as batch_op:
        batch_op.alter_column("locale", nullable=False)

    with op.batch_alter_table("poll_data", schema=None) as batch_op:
        batch_op.alter_column(
            "locale",
            existing_type=postgresql.ENUM(
                "jp", "Ge", "En", "Fr", "Sp", "Du", "It", "ptbr", "ru", name="locale"
            ),
            nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posters", schema=None) as batch_op:
        batch_op.drop_column("locale")

    with op.batch_alter_table("pay_posters", schema=None) as batch_op:
        batch_op.drop_column("locale")

    with op.batch_alter_table("news", schema=None) as batch_op:
        batch_op.drop_column("locale")

    # ### end Alembic commands ###
