"""Rename Miis table

Revision ID: a33eb0efb9b5
Revises: 3d70211feea3
Create Date: 2020-10-24 09:06:13.646798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a33eb0efb9b5"
down_revision = "3d70211feea3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("miis", "concierge_miis")
    op.create_unique_constraint(None, "concierge_miis", ["mii_id"])
    op.drop_constraint("mii_data_mii_id_fkey", "mii_data", type_="foreignkey")
    op.create_foreign_key(None, "mii_data", "concierge_miis", ["mii_id"], ["mii_id"])
    op.drop_constraint("mii_msg_info_mii_id_fkey", "mii_msg_info", type_="foreignkey")
    op.create_foreign_key(
        None, "mii_msg_info", "concierge_miis", ["mii_id"], ["mii_id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "mii_msg_info", type_="foreignkey")
    op.create_foreign_key(
        "mii_msg_info_mii_id_fkey", "mii_msg_info", "miis", ["mii_id"], ["mii_id"]
    )
    op.drop_constraint(None, "mii_data", type_="foreignkey")
    op.create_foreign_key(
        "mii_data_mii_id_fkey", "mii_data", "miis", ["mii_id"], ["mii_id"]
    )
    op.drop_constraint(None, "concierge_miis", type_="unique")
    op.rename_table("concierge_miis", "miis")
    # ### end Alembic commands ###
