"""Remove sppage_id from (Pay)Categories

Revision ID: a61cc98911a3
Revises: 7e2d8bff82e0
Create Date: 2026-07-07 11:25:32.678562

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a61cc98911a3"
down_revision = "7e2d8bff82e0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("test")
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_column("sp_page_id")

    with op.batch_alter_table("pay_categories", schema=None) as batch_op:
        batch_op.drop_column("sp_page_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pay_categories", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("sp_page_id", sa.INTEGER(), autoincrement=False, nullable=True)
        )

    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("sp_page_id", sa.INTEGER(), autoincrement=False, nullable=True)
        )

    op.create_table(
        "test",
        sa.Column("a", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("a", name=op.f("test_pkey")),
    )
    # ### end Alembic commands ###
