"""Add room id to Pay Categories

Revision ID: af7d7a8e8309
Revises: da8e2f3e9887
Create Date: 2024-08-23 23:35:04.358957

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "af7d7a8e8309"
down_revision = "da8e2f3e9887"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pay_categories", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sp_page_id", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pay_categories", schema=None) as batch_op:
        batch_op.drop_column("sp_page_id")

    # ### end Alembic commands ###
