"""Make Mii ID the primary key for Room Miis

Revision ID: b21847b05808
Revises: e40c6d93a515
Create Date: 2024-07-04 22:37:35.247186

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b21847b05808"
down_revision = "e40c6d93a515"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("room_miis", schema=None) as batch_op:
        batch_op.drop_constraint("room_miis_room_id_key", type_="unique")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("room_miis", schema=None) as batch_op:
        batch_op.create_unique_constraint("room_miis_room_id_key", ["room_id"])

    # ### end Alembic commands ###
