"""Remove locale from evaluate and poll data

Revision ID: c0db4fbbc1ed
Revises: 03d6c029c301
Create Date: 2026-06-30 09:27:26.591191

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c0db4fbbc1ed"
down_revision = "03d6c029c301"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("evaluate_data", schema=None) as batch_op:
        batch_op.drop_column("locale")

    with op.batch_alter_table("poll_data", schema=None) as batch_op:
        batch_op.drop_column("locale")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("poll_data", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "locale",
                postgresql.ENUM(
                    "jp",
                    "Ge",
                    "En",
                    "Fr",
                    "Sp",
                    "Du",
                    "It",
                    "ptbr",
                    "ru",
                    name="locale",
                ),
                autoincrement=False,
                nullable=False,
            )
        )

    with op.batch_alter_table("evaluate_data", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "locale",
                postgresql.ENUM(
                    "jp",
                    "Ge",
                    "En",
                    "Fr",
                    "Sp",
                    "Du",
                    "It",
                    "ptbr",
                    "ru",
                    name="locale",
                ),
                autoincrement=False,
                nullable=False,
            )
        )

    # ### end Alembic commands ###
