"""Add Locale enum and columns

Revision ID: cf6f2d53acba
Revises: 70ae2a4487d5
Create Date: 2026-06-28 11:34:54.527781

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "cf6f2d53acba"
down_revision = "70ae2a4487d5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "locale",
                sa.Enum(
                    "jp",
                    "Ge",
                    "En",
                    "Fr",
                    "Sp",
                    "Du",
                    "It",
                    "ptbr",
                    "ru",
                    name="locale",
                ),
                nullable=True,
            )
        )

    op.execute("""UPDATE categories SET locale='En'""")
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.alter_column("locale", nullable=False)

    with op.batch_alter_table("concierge_miis", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "locale",
                sa.Enum(
                    "jp",
                    "Ge",
                    "En",
                    "Fr",
                    "Sp",
                    "Du",
                    "It",
                    "ptbr",
                    "ru",
                    name="locale",
                ),
                nullable=True,
            )
        )

    op.execute("""UPDATE concierge_miis SET locale='En'""")
    with op.batch_alter_table("concierge_miis", schema=None) as batch_op:
        batch_op.alter_column("locale", nullable=False)

    with op.batch_alter_table("evaluate_data", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "locale",
                sa.Enum(
                    "jp",
                    "Ge",
                    "En",
                    "Fr",
                    "Sp",
                    "Du",
                    "It",
                    "ptbr",
                    "ru",
                    name="locale",
                ),
                nullable=True,
            )
        )

    op.execute("""UPDATE evaluate_data SET locale='En'""")
    with op.batch_alter_table("evaluate_data", schema=None) as batch_op:
        batch_op.alter_column("locale", nullable=False)

    with op.batch_alter_table("giveaways", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "locale",
                sa.Enum(
                    "jp",
                    "Ge",
                    "En",
                    "Fr",
                    "Sp",
                    "Du",
                    "It",
                    "ptbr",
                    "ru",
                    name="locale",
                ),
                nullable=True,
            )
        )

    op.execute("""UPDATE giveaways SET locale='En'""")
    with op.batch_alter_table("giveaways", schema=None) as batch_op:
        batch_op.alter_column("locale", nullable=False)

    with op.batch_alter_table("intro_info", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "locale",
                sa.Enum(
                    "jp",
                    "Ge",
                    "En",
                    "Fr",
                    "Sp",
                    "Du",
                    "It",
                    "ptbr",
                    "ru",
                    name="locale",
                ),
                nullable=True,
            )
        )

    op.execute("""UPDATE intro_info SET locale='En'""")
    with op.batch_alter_table("intro_info", schema=None) as batch_op:
        batch_op.alter_column("locale", nullable=False)

    with op.batch_alter_table("movie_credits", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "locale",
                sa.Enum(
                    "jp",
                    "Ge",
                    "En",
                    "Fr",
                    "Sp",
                    "Du",
                    "It",
                    "ptbr",
                    "ru",
                    name="locale",
                ),
                nullable=True,
            )
        )

    op.execute("""UPDATE movie_credits SET locale='En'""")
    with op.batch_alter_table("movie_credits", schema=None) as batch_op:
        batch_op.alter_column("locale", nullable=False)

    with op.batch_alter_table("movies", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "locale",
                sa.Enum(
                    "jp",
                    "Ge",
                    "En",
                    "Fr",
                    "Sp",
                    "Du",
                    "It",
                    "ptbr",
                    "ru",
                    name="locale",
                ),
                nullable=True,
            )
        )

    op.execute("""UPDATE movies SET locale='En'""")
    with op.batch_alter_table("movies", schema=None) as batch_op:
        batch_op.alter_column("locale", nullable=False)

    with op.batch_alter_table("pay_categories", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "locale",
                sa.Enum(
                    "jp",
                    "Ge",
                    "En",
                    "Fr",
                    "Sp",
                    "Du",
                    "It",
                    "ptbr",
                    "ru",
                    name="locale",
                ),
                nullable=True,
            )
        )

    op.execute("""UPDATE pay_categories SET locale='En'""")
    with op.batch_alter_table("pay_categories", schema=None) as batch_op:
        batch_op.alter_column("locale", nullable=False)

    with op.batch_alter_table("pay_movies", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "locale",
                sa.Enum(
                    "jp",
                    "Ge",
                    "En",
                    "Fr",
                    "Sp",
                    "Du",
                    "It",
                    "ptbr",
                    "ru",
                    name="locale",
                ),
                nullable=True,
            )
        )

    op.execute("""UPDATE pay_movies SET locale='En'""")
    with op.batch_alter_table("pay_movies", schema=None) as batch_op:
        batch_op.alter_column("locale", nullable=False)

    with op.batch_alter_table("poll_data", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "locale",
                sa.Enum(
                    "jp",
                    "Ge",
                    "En",
                    "Fr",
                    "Sp",
                    "Du",
                    "It",
                    "ptbr",
                    "ru",
                    name="locale",
                ),
                nullable=True,
            )
        )

    op.execute("""UPDATE pay_movies SET locale='En'""")
    with op.batch_alter_table("pay_movies", schema=None) as batch_op:
        batch_op.alter_column("locale", nullable=False)

    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "locale",
                sa.Enum(
                    "jp",
                    "Ge",
                    "En",
                    "Fr",
                    "Sp",
                    "Du",
                    "It",
                    "ptbr",
                    "ru",
                    name="locale",
                ),
                nullable=True,
            )
        )

    op.execute("""UPDATE rooms SET locale='En'""")
    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.alter_column("locale", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.drop_column("locale")

    with op.batch_alter_table("poll_data", schema=None) as batch_op:
        batch_op.drop_column("locale")

    with op.batch_alter_table("pay_movies", schema=None) as batch_op:
        batch_op.drop_column("locale")

    with op.batch_alter_table("pay_categories", schema=None) as batch_op:
        batch_op.drop_column("locale")

    with op.batch_alter_table("movies", schema=None) as batch_op:
        batch_op.drop_column("locale")

    with op.batch_alter_table("movie_credits", schema=None) as batch_op:
        batch_op.drop_column("locale")

    with op.batch_alter_table("intro_info", schema=None) as batch_op:
        batch_op.drop_column("locale")

    with op.batch_alter_table("giveaways", schema=None) as batch_op:
        batch_op.drop_column("locale")

    with op.batch_alter_table("evaluate_data", schema=None) as batch_op:
        batch_op.drop_column("locale")

    with op.batch_alter_table("concierge_miis", schema=None) as batch_op:
        batch_op.drop_column("locale")

    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_column("locale")

    # ### end Alembic commands ###
