"""Add seq to RoomMiis

Revision ID: da8e2f3e9887
Revises: b21847b05808
Create Date: 2024-07-04 22:41:48.173083

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "da8e2f3e9887"
down_revision = "b21847b05808"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("room_miis", schema=None) as batch_op:
        batch_op.add_column(sa.Column("seq", sa.Integer()))

    op.execute("UPDATE room_miis SET seq = 1")
    op.alter_column(
        "room_miis",
        "seq",
        existing_type=sa.Integer(),
        nullable=False,
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("room_miis", schema=None) as batch_op:
        batch_op.drop_column("seq")

    # ### end Alembic commands ###
