"""Add parade information

Revision ID: e2e07d301565
Revises: c50a32e63543
Create Date: 2020-11-02 20:36:28.598775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e2e07d301565"
down_revision = "c50a32e63543"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parade_miis",
        sa.Column("mii_id", sa.Integer(), nullable=False),
        sa.Column("logo_id", sa.String(length=5), nullable=False),
        sa.Column("logo_bin", sa.String(length=8000), nullable=True),
        sa.ForeignKeyConstraint(
            ["mii_id"],
            ["mii_data.mii_id"],
        ),
        sa.PrimaryKeyConstraint("mii_id", "logo_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("parade_miis")
    # ### end Alembic commands ###
