"""Double primary key for RoomMiis

Revision ID: e40c6d93a515
Revises: 6ebdcbc733bf
Create Date: 2024-07-04 22:34:30.018315

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e40c6d93a515"
down_revision = "6ebdcbc733bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("room_miis", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["room_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("room_miis", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
