"""Add rooms.parade_mii

Revision ID: e4bbd06caf28
Revises: e68011f069bc
Create Date: 2026-05-29 12:12:41.195767

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text
from models import RoomMiis, Rooms

# revision identifiers, used by Alembic.
revision = "e4bbd06caf28"
down_revision = "e68011f069bc"
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.add_column(sa.Column("parade_mii", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "mii_data", ["parade_mii"], ["mii_id"])

    # Gets the first Mii for a room. Content will have to adjust later to have
    # the correct Mii in the parade
    conn = op.get_bind()
    rows = conn.execute(
        text(
            "SELECT rooms.room_id, room_miis.mii_id FROM room_miis, rooms WHERE room_miis.room_id = rooms.room_id"
        )
    )

    # If we've already seen this room then disregard
    seen = set()
    for row in rows:
        if row[0] in seen:
            continue

        # Add room to set
        seen.add(row[0])
        # and update!
        stmt = sa.update(Rooms).values(parade_mii=row[1]).where(Rooms.room_id == row[0])
        batch_op.execute(stmt)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("parade_mii")

    # ### end Alembic commands ###
