"""Add position to intro info

Revision ID: e68011f069bc
Revises: 13768f955d5b
Create Date: 2026-03-01 14:12:09.478387

"""

from alembic import op
from models import IntroInfo
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "e68011f069bc"
down_revision = "13768f955d5b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("intro_info", schema=None) as batch_op:
        # Create column without constraint as we have to add the values manually.
        batch_op.add_column(sa.Column("position", sa.Integer()))

    # Content team will have to adjust later but this will populate the fields.
    conn = op.get_bind()
    stmt = sa.select(IntroInfo).order_by(IntroInfo.cnt_id)
    rows = conn.execute(stmt)
    for i, row in enumerate(rows):
        stmt = (
            sa.update(IntroInfo)
            .values(position=i + 1)
            .where(IntroInfo.cnt_id == row[0])
        )
        batch_op.execute(stmt)

    # Finally add the null constraint.
    op.alter_column(
        "intro_info",
        "position",
        existing_type=sa.Integer(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("intro_info", schema=None) as batch_op:
        batch_op.drop_column("position")

    # ### end Alembic commands ###
