"""Add intro info table

Revision ID: e6c5c826b357
Revises: 24c726f82d58
Create Date: 2022-03-15 14:16:22.531687

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e6c5c826b357"
down_revision = "24c726f82d58"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "intro_info",
        sa.Column(
            "cnt_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            unique=True,
            primary_key=True,
        ),
        sa.Column(
            "cnt_type", sa.Enum("Video", "Image", name="contenttypes"), nullable=True
        ),
        sa.Column("cat_name", sa.String(), nullable=True),
        sa.Column(
            "link_type",
            sa.Enum(
                "Regular",
                "TheatreMovie",
                "TheatreCategory",
                "Shop",
                "Room",
                "Category",
                name="linktypes",
            ),
            nullable=True,
        ),
        sa.Column("link_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("cnt_id"),
        sa.UniqueConstraint("cnt_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("intro_info")
    # ### end Alembic commands ###
