"""Add unlisted column to Movies

Revision ID: f42ed9c3bbc1
Revises: 01cda65b0957
Create Date: 2025-02-03 18:16:16.326263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42ed9c3bbc1'
down_revision = '01cda65b0957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

     # First drop the null constraint.
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unlisted', sa.Boolean(), nullable=True))
    # Set all to false
    op.execute(
        """
        UPDATE movies
        SET unlisted = False
        """
    )

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column("unlisted", existing_type=sa.Boolean(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('unlisted')

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
