"""Use proper binary type

Revision ID: fe7086725145
Revises: e2e07d301565
Create Date: 2020-11-03 05:44:31.097375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fe7086725145"
down_revision = "e2e07d301565"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "parade_miis",
        "logo_bin",
        existing_type=sa.VARCHAR(length=8000),
        type_=sa.Binary(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "parade_miis",
        "logo_bin",
        existing_type=sa.Binary(),
        type_=sa.VARCHAR(length=8000),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
