"""Latest schema

Revision ID: a0b39ad0c389
Revises: 24c726f82d58
Create Date: 2022-02-26 22:33:44.206880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a0b39ad0c389"
down_revision = "24c726f82d58"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "room_miis", ["room_id"])
    op.drop_constraint("room_miis_room_id_fkey", "room_miis", type_="foreignkey")
    op.drop_column("room_miis", "id")
    op.add_column("rooms", sa.Column("news", sa.String(), nullable=True))
    op.drop_constraint("rooms_mii_id_fkey", "rooms", type_="foreignkey")
    op.drop_column("rooms", "mii_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rooms", sa.Column("mii_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_foreign_key(
        "rooms_mii_id_fkey", "rooms", "mii_data", ["mii_id"], ["mii_id"]
    )
    op.drop_column("rooms", "news")
    op.add_column(
        "room_miis", sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False)
    )
    op.create_foreign_key(
        "room_miis_room_id_fkey", "room_miis", "rooms", ["room_id"], ["room_id"]
    )
    op.drop_constraint(None, "room_miis", type_="unique")
    # ### end Alembic commands ###
